In [1]:
from miditok import REMI, CPWord, TokenizerConfig 
from miditoolkit.midi.parser import MidiFile
from pathlib import Path
import tqdm


/home/emma/anaconda3/envs/bai_env310/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# Load the MIDI file
midi_path = './tutorial/000.mid'
midi = MidiFile(midi_path)

# Tokenize the MIDI file
remi_tokenizer = REMI()
tokens = remi_tokenizer(midi)
print(type(tokens), tokens)

# Retrieve the event-to-token mapping dictionary
event_to_token_mapping = remi_tokenizer.vocab
print(type(event_to_token_mapping))
event_to_token_mapping


<class 'list'> [TokSequence(tokens=['Bar_None', 'Position_6', 'Pitch_43', 'Velocity_51', 'Duration_3.4.8', 'Pitch_50', 'Velocity_39', 'Duration_3.3.8', 'Position_7', 'Pitch_54', 'Velocity_55', 'Duration_3.4.8', 'Pitch_69', 'Velocity_51', 'Duration_1.2.8', 'Pitch_71', 'Velocity_59', 'Duration_3.3.8', 'Position_8', 'Pitch_74', 'Velocity_59', 'Duration_3.1.8', 'Pitch_78', 'Velocity_79', 'Duration_3.2.8', 'Bar_None', 'Position_0', 'Pitch_76', 'Velocity_63', 'Duration_4.0.4', 'Pitch_81', 'Velocity_71', 'Duration_4.2.4', 'Pitch_52', 'Velocity_47', 'Duration_4.0.4', 'Pitch_64', 'Velocity_51', 'Duration_5.1.4', 'Pitch_69', 'Velocity_59', 'Duration_4.0.4', 'Pitch_74', 'Velocity_55', 'Duration_0.3.8', 'Bar_None', 'Position_0', 'Pitch_45', 'Velocity_63', 'Duration_4.1.4', 'Pitch_52', 'Velocity_59', 'Duration_4.2.4', 'Pitch_69', 'Velocity_67', 'Duration_4.2.4', 'Pitch_76', 'Velocity_71', 'Duration_4.0.4', 'Pitch_71', 'Velocity_63', 'Duration_4.0.4', 'Pitch_74', 'Velocity_59', 'Duration_7.0.4', 'Ba

/tmp/ipykernel_5885/1160858956.py:9: UserWarning: You are using a depreciated `miditoolkit.MidiFile` object. MidiTokis now (>v3.0.0) using symusic.Score as MIDI backend. Your file willbe converted on the fly, however please consider using symusic.
  tokens = remi_tokenizer(midi)


{'PAD_None': 0,
 'BOS_None': 1,
 'EOS_None': 2,
 'MASK_None': 3,
 'Bar_None': 4,
 'Pitch_21': 5,
 'Pitch_22': 6,
 'Pitch_23': 7,
 'Pitch_24': 8,
 'Pitch_25': 9,
 'Pitch_26': 10,
 'Pitch_27': 11,
 'Pitch_28': 12,
 'Pitch_29': 13,
 'Pitch_30': 14,
 'Pitch_31': 15,
 'Pitch_32': 16,
 'Pitch_33': 17,
 'Pitch_34': 18,
 'Pitch_35': 19,
 'Pitch_36': 20,
 'Pitch_37': 21,
 'Pitch_38': 22,
 'Pitch_39': 23,
 'Pitch_40': 24,
 'Pitch_41': 25,
 'Pitch_42': 26,
 'Pitch_43': 27,
 'Pitch_44': 28,
 'Pitch_45': 29,
 'Pitch_46': 30,
 'Pitch_47': 31,
 'Pitch_48': 32,
 'Pitch_49': 33,
 'Pitch_50': 34,
 'Pitch_51': 35,
 'Pitch_52': 36,
 'Pitch_53': 37,
 'Pitch_54': 38,
 'Pitch_55': 39,
 'Pitch_56': 40,
 'Pitch_57': 41,
 'Pitch_58': 42,
 'Pitch_59': 43,
 'Pitch_60': 44,
 'Pitch_61': 45,
 'Pitch_62': 46,
 'Pitch_63': 47,
 'Pitch_64': 48,
 'Pitch_65': 49,
 'Pitch_66': 50,
 'Pitch_67': 51,
 'Pitch_68': 52,
 'Pitch_69': 53,
 'Pitch_70': 54,
 'Pitch_71': 55,
 'Pitch_72': 56,
 'Pitch_73': 57,
 'Pitch_74': 58,
 'Pitc

In [3]:
print('Tokenizing source MIDI file...')

# parameters
TOKENIZER_PARAMS = {
    "pitch_range": (21, 109),
    "beat_res": {(0, 4): 8, (4, 12): 4},
    "num_velocities": 50,
    "special_tokens": ["PAD", "BOS", "EOS", "MASK", "OOV"],
    "use_chords": True,
    "use_rests": False,
    "use_tempos": True,
    "use_time_signatures": False,
    "use_programs": False,
    "num_tempos": 32,  # nb of tempo bins
    "tempo_range": (40, 250),  # (min, max)
    "rest_range": (2, 8),  # (half, 8 beats)
}
config = TokenizerConfig(**TOKENIZER_PARAMS)

# Creates the tokenizer and loads a MIDI
tokenizer = REMI(config) # REMI encoding
# tokenizer = CPWord(config) # CP encoding

# Converts MIDI to tokens, and back to a MIDI
### NOTE: find out the MidiFile is deprecated from MidiTok Library. The tokenizer can directly operate on midi file path
# midi = MidiFile(midi_path) 
tokens = tokenizer(midi_path)
print(tokens)

Tokenizing source MIDI file...
[TokSequence(tokens=['Bar_None', 'Position_0', 'Tempo_46.77', 'Position_6', 'Pitch_43', 'Velocity_53', 'Duration_3.4.8', 'Pitch_50', 'Velocity_38', 'Duration_3.3.8', 'Position_7', 'Pitch_54', 'Velocity_55', 'Duration_3.4.8', 'Pitch_69', 'Velocity_50', 'Duration_1.2.8', 'Pitch_71', 'Velocity_58', 'Duration_3.3.8', 'Position_8', 'Tempo_73.87', 'Pitch_74', 'Velocity_58', 'Duration_3.1.8', 'Pitch_78', 'Velocity_78', 'Duration_3.2.8', 'Position_16', 'Tempo_80.65', 'Position_24', 'Tempo_73.87', 'Bar_None', 'Position_0', 'Tempo_73.87', 'Pitch_76', 'Velocity_60', 'Duration_4.0.4', 'Pitch_81', 'Velocity_68', 'Duration_4.2.4', 'Pitch_52', 'Velocity_48', 'Duration_4.0.4', 'Pitch_64', 'Velocity_53', 'Duration_5.1.4', 'Pitch_69', 'Velocity_58', 'Duration_4.0.4', 'Pitch_74', 'Velocity_55', 'Duration_0.3.8', 'Position_8', 'Tempo_67.1', 'Position_16', 'Tempo_73.87', 'Position_24', 'Tempo_80.65', 'Bar_None', 'Position_0', 'Tempo_87.42', 'Pitch_45', 'Velocity_60', 'Duratio

In [4]:
from torch.utils.data.dataloader import DataLoader, Dataset
import torch
import numpy as np
X_LEN = 512

In [20]:
class Pop1K7Dataset(Dataset):
    def __init__(self, midi_dataset_path = "./Pop1K7/midi_analyzed/", prompt = ''):
        self.x_len = X_LEN
        self.tokenizer = None
        self.midi_paths = list(Path(midi_dataset_path).glob('**/*.mid'))
        self.parser = self.prepare_data(self.midi_paths)
    
    def get_tokenizer(self):
        if self.tokenizer is None:
            raise NotImplementedError("The tokenizer has not been initialized")
        return self.tokenizer

    def __len__(self):
        return len(self.parser)  
    
    def __getitem__(self, index):
        return self.parser[index]

    def initialize_tokenizer(self):
        if self.tokenizer is not None:
            print("The tokenizer has already been initialized.")
        
        TOKENIZER_PARAMS = {
            "pitch_range": (21, 109),
            "beat_res": {(0, 4): 8, (4, 12): 4},
            "num_velocities": 50,
            "special_tokens": ["PAD", "BOS", "EOS", "MASK", "OOV"],
            "use_chords": True,
            "use_rests": True,
            "use_tempos": True,
            "use_time_signatures": False,
            "use_programs": False,
            "num_tempos": 32,  # nb of tempo bins
            "tempo_range": (40, 250),  # (min, max)
            "rest_range": (2, 8),  # (half, 8 beats)
        }
        config = TokenizerConfig(**TOKENIZER_PARAMS)
        self.tokenizer = REMI(config) # REMI encoding
    
    def prepare_data(self, midi_paths):
        """extract events(tokens) and words(ids)"""
        if self.tokenizer is None:
            self.initialize_tokenizer()
        
        all_tokens = []
        all_ids = []
        pbar = tqdm.tqdm(midi_paths, disable=False) # disable=args.quiet
        pbar.set_description("Tokenizing MIDI Files")
        for path in pbar:
            tok_sequence = self.tokenizer(path)[0]
            tokens = tok_sequence.tokens
            ids = tok_sequence.ids
            all_tokens.append(tokens)
            all_ids.append(ids)
        
        # all_ids is a list containing ids list of all midi files
        # all_ids = [[token_ids of midi], [token_ids of midi], ...]

        # TODO: cut the data size to feed into model
        # Warning : this example cannot use in transformer_XL, you must implement group segments by yourself
        segments = []
        pbar = tqdm.tqdm(all_ids, disable=False) # disable=args.quiet
        pbar.set_description("Preparing Sample Pairs")
        for words in pbar:
            pairs = []
            for i in range(0, len(words)-self.x_len-1, self.x_len // 4):
                x = words[i:i+self.x_len]
                y = words[i+1:i+self.x_len+1]
                pairs.append([x, y])
            # abandon last segments in a midi
            pairs = pairs[0:len(pairs)-(len(pairs)%5)]
            segments = segments + pairs
        segments = torch.tensor(segments)
        print(segments.shape)
        return segments

In [21]:
dataset = Pop1K7Dataset()
print(len(dataset))

Preparing Sample Pairs: 100%|██████████| 1747/1747 [00:01<00:00, 1163.85it/s]


torch.Size([59870, 2, 512])
59870


In [22]:
for d in dataset:
    x, y = d
    print(x.size(), y.size())
    print(x[:10])
    print(y[:10])
    break

torch.Size([512]) torch.Size([512])
tensor([  5, 208, 359, 328, 232, 347, 322, 208, 360,  41])
tensor([208, 359, 328, 232, 347, 322, 208, 360,  41, 118])


In [23]:
print(set([token.split('_')[0] for token in tokenizer.vocab.keys()]))
[token for token in tokenizer.vocab.keys() if token.startswith('Chord')]

{'OOV', 'PAD', 'BOS', 'Bar', 'MASK', 'Chord', 'Rest', 'Tempo', 'PitchDrum', 'Position', 'Duration', 'Pitch', 'Velocity', 'EOS'}


['Chord_min',
 'Chord_maj',
 'Chord_dim',
 'Chord_aug',
 'Chord_sus2',
 'Chord_sus4',
 'Chord_7dom',
 'Chord_7min',
 'Chord_7maj',
 'Chord_7halfdim',
 'Chord_7dim',
 'Chord_7aug',
 'Chord_9maj',
 'Chord_9min']

In [24]:
# word2event = {v: k for k, v in tokenizer.vocab.items()}
# word2event[0]
# yt = y.unsqueeze(0)
# gen_midi = tokenizer(yt)
# gen_midi.dump_midi("tmp.mid")


In [25]:
from transformers import GPT2Config, GPT2LMHeadModel

In [26]:
tokenizer = dataset.get_tokenizer()
config = {
    'vocab_size': tokenizer.vocab_size,
    'eos_token_id': tokenizer.vocab['EOS_None'],
    'bos_token_id': tokenizer.vocab['BOS_None'],
    'pad_token_id': tokenizer.vocab['PAD_None'],
    'mask_token_id': tokenizer.vocab['MASK_None'],
    'oov_token_id': tokenizer.vocab['OOV_None'],
}

model_config = GPT2Config(**config)
model = GPT2LMHeadModel(model_config)

In [27]:
model_config

GPT2Config {
  "activation_function": "gelu_new",
  "attn_pdrop": 0.1,
  "bos_token_id": 1,
  "embd_pdrop": 0.1,
  "eos_token_id": 2,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "mask_token_id": 3,
  "model_type": "gpt2",
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "oov_token_id": 4,
  "pad_token_id": 0,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.44.2",
  "use_cache": true,
  "vocab_size": 379
}

In [28]:
x = torch.randint(0, model_config.vocab_size, (1, 512), dtype=torch.int)
y = model(x)

In [29]:
print(y.logits.size())

torch.Size([1, 512, 379])


In [30]:
import torch.nn as nn
output = nn.Softmax(dim=-1)(y.logits)
output = output.permute(0,2,1)
print(output.size())
print(x.size())
loss = nn.CrossEntropyLoss()(y.logits.permute(0,2,1)[..., -1], x.long()[..., -1])
print(loss)

torch.Size([1, 379, 512])
torch.Size([1, 512])
tensor(4.0201, grad_fn=<NllLossBackward0>)


In [50]:
from model import GPT2Model
import os
checkpoint = torch.load("model_checkpoints/epoch_001.pkl")

model_new = GPT2Model(tokenizer)
model_new = torch.nn.DataParallel(model_new)
model_new.to('cuda')
torch.save(
    {
        "model_state_dict": model.state_dict(),
    },
    os.path.join("model_checkpoints", "tmp.pkl"),
)
# model_new = model.load_state_dict(checkpoint['model'], strict=False)

In [52]:
# model_new.state_dict()

In [53]:
checkpoint = torch.load("./model_checkpoints/tmp.pkl", map_location='cpu')
checkpoint["model_state_dict"]

OrderedDict([('model.transformer.wte.weight',
              tensor([[ 0.0059,  0.0047,  0.0127,  ..., -0.0073,  0.0037, -0.0261],
                      [-0.0059,  0.0317, -0.0132,  ...,  0.0034,  0.0256,  0.0009],
                      [-0.0136,  0.0046,  0.0088,  ...,  0.0086,  0.0023,  0.0033],
                      ...,
                      [ 0.0046, -0.0032,  0.0132,  ...,  0.0258, -0.0174, -0.0208],
                      [-0.0119, -0.0187, -0.0054,  ..., -0.0089, -0.0212, -0.0160],
                      [ 0.0285, -0.0042, -0.0174,  ..., -0.0018,  0.0232,  0.0306]])),
             ('model.transformer.wpe.weight',
              tensor([[ 0.0460, -0.0302, -0.0296,  ...,  0.0052,  0.0367, -0.0146],
                      [-0.0259, -0.0329,  0.0029,  ...,  0.0215, -0.0132, -0.0052],
                      [-0.0085,  0.0070,  0.0228,  ...,  0.0120,  0.0292, -0.0358],
                      ...,
                      [ 0.0378,  0.0035,  0.0341,  ...,  0.0121, -0.0005, -0.0113],
           